frontend/urls.py
from django.conf import settings
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView

from frontend.views import AboutView, ComponentView, PlayerExportView, PlayerImportView, WorldComponentView
from unicorn_viewsets.routers import Router

router = Router(view_class=ComponentView)
router.register("backstage-users", "backstage-users")
router.register("players", "players")
router.register("worlds", "worlds")
router.register("tags", "tags")
router.register("character-textures", "character-textures")

world_router = Router(view_class=WorldComponentView)
world_router.register("rooms", "rooms")
world_router.register("players", "world-memberships")
world_router.register("character-textures", "character-textures")
world_router.register("bans", "bans")

urlpatterns = [
    path("", include(router.urls)),
    path("", RedirectView.as_view(url=settings.LOGIN_REDIRECT_URL), name="index"),
    path("about/", AboutView.as_view(), name="about"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("css-components/", TemplateView.as_view(template_name="css-components/css-components.html")),
    path("profile/edit/", ComponentView.as_view(component_name="profile"), name="profile-update"),
    path("worlds/<int:world_pk>/", include(world_router.urls)),
    path(
        "worlds/<int:world_pk>/bans/add/('<uuid:membership_pk>')/",
        ComponentView.as_view(component_name="bans"),
        name="bans-create",
    ),
    path("worlds/<int:world_pk>/players/export/", PlayerExportView.as_view(), name="export-world-players"),
    path("worlds/<int:world_pk>/players/import/", PlayerImportView.as_view(), name="import-world-players"),
]

wa_api/urls.py
# python imports

# django imports
from django.urls import include, path
from rest_framework import routers
from rest_framework.schemas import get_schema_view

# project imports
from wa_api.views import CheckBanView, MapView, ReportView, RoomAccessView, LoginUrlView, RoomSameWorldView

# define DRF routes
router = routers.DefaultRouter()

# define django routes
urlpatterns = [
    path("", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path(
        "openapi",
        get_schema_view(
            title="WA admin API",
            description="The API used by connected WA instances.",
            version="1.0.0",
            urlconf="wa_api.urls",
        ),
        name="wa_api-openapi-schema",
    ),
    path("ban", CheckBanView.as_view()),
    path("map", MapView.as_view()),
    path("report", ReportView.as_view()),
    path("room/access", RoomAccessView.as_view()),
    path("login-url/<uuid:pk>/", LoginUrlView.as_view()),
    path("room/sameWorld", RoomSameWorldView.as_view()),
]

core/models.py
# python imports
import uuid

# django imports
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models

from django.utils.translation import gettext_lazy as _
from django.core.validators import RegexValidator

# from django.contrib.admin import templates.registration.pa
# projects import
from core.utils import SingletonModel


class PolicyType(models.IntegerChoices):
    ANONYMOUS = 1, _("Any player may use")
    MEMBERS_ONLY = 2, _("Only world members may use")
    USE_TAGS = 3, _("Players with room tags may use")


class BackstageUser(AbstractUser):
    email = models.EmailField(_("email"), unique=True)


class Tag(models.Model):
    name = models.CharField(max_length=80, verbose_name=_("Name"))
    description = models.TextField(verbose_name=_("Description"), blank=True)

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")
        ordering = ["name"]

    def __str__(self):
        return self.name


class AdminTag(SingletonModel, Tag):
    class Meta:
        verbose_name = _("Admin Tag")

    def __eq__(self, other):
        assert isinstance(other, Tag)
        pk = self.load().pk
        if pk is None:
            return self is other
        return pk == other.pk

    def save(self, *args, **kwargs):
        self.name = "admin"
        return super().save(*args, **kwargs)


class CharacterTexture(models.Model):
    name = models.CharField(max_length=80, verbose_name=_("Name"))
    texture_id = models.IntegerField(verbose_name=_("Texture ID"))
    level = models.IntegerField(verbose_name=_("Level"))
    # rights implemented in WA without any functionality 02/22
    # maybe some tagging feature was planed once
    # not implemented in WA Code
    # a wa-backstage implementation is provided
    policy_type = models.IntegerField(
        verbose_name=_("Policy Type"), choices=PolicyType.choices, default=PolicyType.ANONYMOUS
    )
    tags = models.ManyToManyField(Tag, verbose_name=_("Tags"), blank=True)
    worlds = models.ManyToManyField(
        "World", through="core.world_character_textures", verbose_name=_("Worlds"), blank=True
    )
    url = models.CharField(max_length=1024, verbose_name=_("URL"))
    is_deactivated = models.BooleanField(verbose_name=_("Is deactivated?"), default=False)

    class Meta:
        verbose_name = _("Character Texture")
        verbose_name_plural = _("Character Textures")
        ordering = ["texture_id"]


class World(models.Model):
    name = models.CharField(max_length=80, verbose_name=_("Name"))
    slug = models.CharField(max_length=100, blank=True, unique=True)
    description = models.TextField(verbose_name=_("Description"), blank=True)
    url = models.CharField(max_length=1024, verbose_name=_("URL"), blank=True)
    players = models.ManyToManyField("Player", through="MembershipWorld", related_name="worlds")
    contact_page = models.CharField(max_length=1024, verbose_name=_("Contact Page"), blank=True)
    # oauth provider is configured per WA instance env
    # this is automatically turned off for policy_type 1
    use_oauth = models.BooleanField(verbose_name=_("Redirect to oauth provider?"), default=False)
    character_textures = models.ManyToManyField(
        CharacterTexture,
        verbose_name=_("Character Texture"),
        blank=True,
    )

    class Meta:
        verbose_name = _("World")
        verbose_name_plural = _("Worlds")
        ordering = ["name"]

    def __str__(self):
        return self.name


class Room(models.Model):
    name = models.CharField(max_length=80, verbose_name=_("Name"))
    description = models.TextField(verbose_name=_("Description"), blank=True)
    url = models.CharField(max_length=1024, verbose_name=_("URL"), blank=True)
    map_url = models.URLField(
        max_length=1024,
        verbose_name=_("Map URL"),
        blank=True,
        error_messages={"invalid": "You need to enter a valid URL that also points to a JSON file."},
        validators=[RegexValidator(r"[\s\S]*\.json$", message=_("Map URL needs to point to a json file."))],
    )
    is_entry_room = models.BooleanField(verbose_name=_("Is entry room of world?"))
    world = models.ForeignKey(World, verbose_name=_("World"), on_delete=models.CASCADE, related_name="rooms")
    room_contact_page = models.CharField(max_length=1024, verbose_name=_("Contact Page"), blank=True)
    analytics_group = models.CharField(max_length=80, verbose_name=_("Name"), blank=True)

    tags = models.ManyToManyField(
        Tag,
        related_name="room_tags",
        verbose_name=_("Room Tags"),
        blank=True,
    )
    policy_type = models.IntegerField(
        verbose_name=_("Policy Type"), choices=PolicyType.choices, default=PolicyType.MEMBERS_ONLY
    )
    is_deactivated = models.BooleanField(verbose_name=_("Is deactivated?"), default=False)

    @property
    def contact_page(self):
        """
        We use contact page URL of world if not specified on room
        """
        if self.room_contact_page:
            return self.room_contact_page
        else:
            return self.world.contact_page

    class Meta:
        verbose_name = _("Room")
        verbose_name_plural = _("Rooms")
        ordering = ["name"]

    def __str__(self):
        return self.name


class Player(models.Model):
    username = models.CharField(max_length=80, verbose_name=_("Username"))
    email = models.EmailField(verbose_name=_("Email Address"))
    comment = models.TextField(verbose_name=_("Comment"), blank=True)

    class Meta:
        verbose_name = _("Player")
        verbose_name_plural = _("Players")
        ordering = ["username"]

    def __str__(self):
        return self.username


class MembershipWorldQuerySet(models.QuerySet):
    def exclude_anonymous(self):
        return self.exclude(anonymous=True)


class MembershipWorld(models.Model):
    uuid_token = models.UUIDField(verbose_name=_("Access Token"), primary_key=True, default=uuid.uuid4)
    player = models.ForeignKey(
        Player, verbose_name=_("Player"), on_delete=models.CASCADE, related_name="world_memberships"
    )
    world = models.ForeignKey(World, verbose_name=_("World"), on_delete=models.CASCADE, related_name="memberships")
    tags = models.ManyToManyField(Tag, verbose_name=_("Tags"), blank=True)
    character_textures = models.ManyToManyField(CharacterTexture, verbose_name=_("Character Textures"), blank=True)
    anonymous = models.BooleanField(default=False, verbose_name=_("Anonymous Player?"))
    visit_card_url = models.CharField(max_length=1024, verbose_name=_("Visit card url"), blank=True)

    objects = models.Manager.from_queryset(MembershipWorldQuerySet)()

    class Meta:
        verbose_name = _("World Membership")
        verbose_name_plural = _("World Memberships")
        ordering = ["player__username"]
        unique_together = ["player", "world"]

    def __str__(self):
        return _("Membership: ") + self.player.username

    def get_world_access_url(self):
        return settings.WORLD_ACCESS_URL_FORMAT.format(world_url=self.world.url, access_token=self.uuid_token)

    def is_admin(self):
        return AdminTag() in self.tags.all()


class Ban(models.Model):
    membership_world = models.ForeignKey(
        MembershipWorld, verbose_name=_("World Membership"), on_delete=models.CASCADE, related_name="bans"
    )
    room = models.ForeignKey(
        Room,
        verbose_name=_("Room"),
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="bans",
    )
    message = models.CharField(max_length=140, verbose_name=_("Message"), blank=True)

    class Meta:
        verbose_name = _("Ban")
        verbose_name_plural = _("Bans")
        # unique_together = [["membership_world", "room"]]
        constraints = [
            models.UniqueConstraint(fields=["membership_world", "room"], name="unique_room_ban"),
            models.UniqueConstraint(
                fields=["membership_world"], condition=models.Q(room=None), name="unique_world_ban"
            ),
        ]

    def __str__(self):
        player_name = self.membership_world.player.username
        # world_name = self.membership_world.world.name
        # room_name = f"({self.room.name})" if self.room else ""
        return _("{}").format(player_name)


class Report(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Report time"))
    room = models.ForeignKey(Room, verbose_name=_("Room"), on_delete=models.CASCADE, related_name="reports")
    user_comment = models.CharField(max_length=250, verbose_name=_("Comment"))
    reported_user = models.ForeignKey(
        Player, verbose_name=_("Player"), on_delete=models.CASCADE, related_name="reported"
    )
    reporter_user = models.ForeignKey(
        Player, verbose_name=_("Player"), on_delete=models.CASCADE, related_name="reporter"
    )

    class Meta:
        verbose_name = _("Report")
        verbose_name_plural = _("Reports")
        ordering = ["-created_at"]

frontend/views.py
import urllib.parse

from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import FormView, TemplateView
from django.views.generic.detail import SingleObjectMixin

from core.models import World
from frontend.admin import import_players, PlayerResource
from frontend.forms import ImportForm
from unicorn_viewsets import views
from wa_backstage import __version__


class ReferralMixin:
    REFERRER_PARAMETER_NAME = "next"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.referrer = self.request.GET.get(self.REFERRER_PARAMETER_NAME, "")

    def needs_page_reload(self):
        return bool(self.referrer)

    def get_success_url(self):
        return urllib.parse.unquote(self.referrer) or super().get_success_url()


class AboutView(TemplateView):
    template_name = "frontend/about.html"

    def get_context_data(self, **kwargs):
        kwargs["version"] = __version__
        return super().get_context_data(**kwargs)


class ComponentView(views.ComponentView):
    template_name = "frontend/component.html"


class WorldComponentView(SingleObjectMixin, views.ComponentView):
    model = World
    object = None
    pk_url_kwarg = "world_pk"
    template_name = "frontend/component_world.html"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class CSVResponse(HttpResponse):
    def __init__(self, content, filename, *args, **kwargs):
        super().__init__(content, content_type="text/csv")
        self["Content-Disposition"] = 'attachment; filename="{}"'.format(filename)


class PlayerExportView(View):
    def get(self, request, *args, **kwargs):
        world = get_object_or_404(World, pk=kwargs.get("world_pk"))
        dataset = PlayerResource(world).export()
        return CSVResponse(dataset.csv, "Players.csv")


class PlayerImportView(FormView):
    template_name = "frontend/import.html"
    form_class = ImportForm
    success_url = reverse_lazy("worlds")

    def form_valid(self, form):
        world = get_object_or_404(World, pk=self.kwargs.get("world_pk"))
        import_players(form.cleaned_data["file"], world)
        return super().form_valid(form)

frontend/templates/unicorn/backstage-users-create.html
{% load i18n %}

{% if unicorn.errors %}
  {% include 'frontend/partials/error.html' %}
{% endif %}

{% include "frontend/partials/heading.html" with title=_("Create User") %}

<form u:submit.prevent="validate_and_create" id="add_user" aria-label="{% translate "Create user" %}"
    {% include "frontend/partials/form_attrs.html" %}>

  {% include "frontend/partials/form_input.html" with label=_("Username") id="username" unicorn_model="username" %}
  {% include "frontend/partials/form_input.html" with type="email" label=_("Email address") id="email" unicorn_model="email" %}
  {% include "frontend/partials/form_buttons.html" %}

</form>

frontend/templates/unicorn/bans-create.html
{% load i18n %}
{% load frontend %}

<div class="mx-4">
    {% if unicorn.errors %}
        {% include 'frontend/partials/error.html' %}
    {% endif %}

    {% if is_world_banned %}
        {% include 'frontend/partials/error.html' with custom_header="Warning" custom_content="You have already banned this member from this whole world. You have to select a room to proceed. If you only want to ban the player from that particular room, you need to remove the world ban afterwards." %}
    {% endif  %}
    {% include "frontend/partials/heading.html" with title=_("Create ban for") additional_information=membership_world.player %}
    <form u:submit.prevent="validate_and_create" id="add_player" aria-label="{% translate "Create ban" %}"
          {% include "frontend/partials/form_attrs.html" %}>

        {% include "frontend/partials/form_select.html" with label=_("Room") id="room" unicorn_model="room" choices=rooms explicit_attribute_access=True user_hint=_("Only rooms with restrictive access policy selectable. Bans for rooms with \"Any player may use\" policy have no effect.") %}
        {% include "frontend/partials/form_input.html" with label=_("Message") id="message" unicorn_model="message" user_hint=_("This message will be displayed to the player.") %}
        {% include "frontend/partials/form_buttons.html" %}
    </form>
</div>

frontend/templates/unicorn/bans-update.html
{% load i18n %}
{% load frontend %}
<div class="mx-4">
    {% if unicorn.errors %}
        {% include 'frontend/partials/error.html' %}
    {% endif %}
    {% include "frontend/partials/heading.html" with title=_("Edit ban for ") level='h2' additional_information=membership_world.player %}
    <form u:submit.prevent="validate_and_update" id="edit_ban" aria-label="{% translate "Edit ban" %} "
          {% include "frontend/partials/form_attrs.html" %}>
        {% include "frontend/partials/form_input.html" with label=_("Message") id="message" unicorn_model="message" %}
        {% include "frontend/partials/form_buttons.html" %}
    </form>
</div>

frontend/templates/unicorn/bans.html
{% load frontend %}
{% load i18n %}
{% load static %}

<div class="mx-4">
    <table aria-label="{% translate "Player list" %}" {% include "frontend/partials/table_attrs.html" %}>
        <thead>
            <tr {% include "frontend/partials/table_head_row_attrs.html" %}>
                {% include "frontend/partials/table_head_col.html" with title=_("") %}
                {% include "frontend/partials/table_head_col.html" with title=_("Name") %}
                {% include "frontend/partials/table_head_col.html" with title=_("Room") %}
                {% include "frontend/partials/table_head_col.html" with title=_("Message") %}
                {% include "frontend/partials/table_head_col.html" with title=_("Actions") align="right" %}
            </tr>
        </thead>
        <tbody {% include "frontend/partials/table_body_attrs.html" %}>
            {% for ban in object_list %}
                <tr {% include "frontend/partials/table_row_attrs.html" with inactive_criterion=ban.room|isopenforall %}>
                    {% include "frontend/partials/table_cell.html" with  is_open_for_all_room=ban.room.policy_type|openforall  only %}
                    {% include "frontend/partials/table_cell.html" with content=ban inactive_criterion=ban.room|isopenforall %}
                    {% include "frontend/partials/table_cell.html" with content=ban.room|ifnoroomall inactive_criterion=ban.room|isopenforall %}
                    {% if ban.message %}
                        {% include "frontend/partials/table_cell.html" with title=_("Message") content=ban.message only %}
                    {% else %}
                        <td class="hidden lg:table-cell"></td>
                    {% endif %}
                    <td {% include "frontend/partials/table_cell_attrs.html" with type="actions" %}>
                        {% include "frontend/partials/table_actions_header.html" %}
                        <div {% include "frontend/partials/table_responsive_attrs.html" %}>
                            {% include "frontend/partials/button_icon.html" with icon="icons/pencil-alt.svg" unicorn_action="show_update"|withparam:ban.pk title=_("Edit ban") aria_label=_("Edit ban data") %}
                            {% include "frontend/partials/button_icon.html" with icon="icons/user-allow.svg" unicorn_action="delete"|withparam:ban.pk title=_("Remove ban") aria_label=_("Remove ban") %}
                        </div>
                    </td>
                </tr>

            {% endfor %}
        </tbody>
    </table>


    <script type="text/javascript">
     function copyToClipboard(id) {
         let value = document.getElementById(id).href
         navigator.clipboard.writeText(value)
     }
    </script>

frontend/templates/unicorn/character-textures-update.html
{% load i18n %}
{% load frontend %}

{% if unicorn.errors %}
    {% include 'frontend/partials/error.html' %}
{% endif %}

{% if not world  %}
  {% include "frontend/partials/heading.html" with title=_("Edit character texture") filter_choices=None %}
{% else %}
{% include "frontend/partials/heading.html" with title=_("Edit character texture") filter_choices=None level="h2" %}
{% endif %}

<div class="flex flex-col md:flex-row gap-x-7">
  {% if url %}
    <div class="h-64 md:h-96 self-center md:self-start mb-5">
      <img src="{{url}}" class="h-full mt-5"\>
    </div>
  {% endif %}
    <form u:submit.prevent="validate_and_update" id="add_player" aria-label="{% translate "Edit character texture" %}"
        {% include "frontend/partials/form_attrs.html" %}>
      {% include "frontend/partials/form_input.html" with label=_("Name") id="name" unicorn_model="name" %}
      {% include "frontend/partials/form_input.html" with label=_("URL") id="url" unicorn_model="url" placeholder="https://my-storage.org/my-texture.png" %}
      {% include "frontend/partials/form_input.html" with label=_("ID") id="texture_id" unicorn_model="texture_id" type="number" %}
      {% include "frontend/partials/form_input.html" with label=_("Level") id="level" unicorn_model="level" type="number" %}
      {% include "frontend/partials/form_select.html" with label=_("Policy Type") id="policy_type" unicorn_model="policy_type" choices=policy_type_choices%}
      {% filterselect_widget "tags" _("Tags search") _("Tags") %}
      {% if not world %}{% filterselect_widget "worlds" _("Worlds search") _("Worlds") %}{% endif %}
      <div class="py-5">
        {% include "frontend/partials/form_input.html" with type="checkbox" label=_("Deactivated") id="is_deactivated" unicorn_model="is_deactivated" %}
      </div>
      {% include "frontend/partials/form_buttons.html" %}
    </form>
</div>

frontend/templates/unicorn/character-textures.html
{% load frontend %}
{% load i18n %}
{% load static %}

{% if not world  %}
  {% include "frontend/partials/heading.html" with title=_("Character textures") button_label=_("Create character texture") button_aria_label=_("Create Character Texture") button_unicorn_action="show_create" %}
    <div class="bg-grey-2 my-4">
      {% include "frontend/partials/form_select.html" with label=_("Select worlds to display") id="filter_choices" unicorn_model="selected_filter_choice" choices=filter_choices%}
    </div>
{% endif %}
  <table aria-label="{% translate "Character texture list" %}" {% include "frontend/partials/table_attrs.html" %}>
    <thead>
    <tr {% include "frontend/partials/table_head_row_attrs.html" %}>
      {% include "frontend/partials/table_head_col.html" with title="" %}
      {% include "frontend/partials/table_head_col.html" with title=_("Name") %}
      {% include "frontend/partials/table_head_col.html" with title=_("ID") %}
      {% include "frontend/partials/table_head_col.html" with title=_("Level") %}
      {% include "frontend/partials/table_head_col.html" with title=_("Policy") %}
      {% include "frontend/partials/table_head_col.html" with title=_("Tags") %}
      {% include "frontend/partials/table_head_col.html" with title=_("Worlds") %}
      {% include "frontend/partials/table_head_col.html" with title=_("Actions") align="right" %}
    </tr>
    </thead>

  <tbody {% include "frontend/partials/table_body_attrs.html" %}>
  {% for character_texture in filtered_list %}

      <tr {% include "frontend/partials/table_row_attrs.html" %}>
        <td {% include "frontend/partials/table_cell_attrs.html" %}>
          <img src="{{character_texture.url}}" class="h-10 w-10"\>
        </td>
        {% include "frontend/partials/table_cell.html" with title=_("Name") content=character_texture.name %}
        {% include "frontend/partials/table_cell.html" with title=_("ID") content=character_texture.texture_id %}
        {% include "frontend/partials/table_cell.html" with title=_("Level") content=character_texture.level %}
        {% include "frontend/partials/table_cell.html" with title=_("Policy") content=character_texture.get_policy_type_display %}
        {% if character_texture.tags.all %}
          {% include "frontend/partials/table_cell.html" with title=_("Tags") content=character_texture.tags.all|join:", " %}
        {% else %}
          <td class="hidden lg:table-cell"></td>
        {% endif %}
        {% if character_texture.world_set.all %}
          {% include "frontend/partials/table_cell.html" with title=_("Worlds") content=character_texture.world_set.all|join:", " %}
        {% else %}
          <td class="hidden lg:table-cell"></td>
        {% endif %}
        <td {% include "frontend/partials/table_cell_attrs.html" with type="actions" %}>
          {% include "frontend/partials/table_actions_header.html" %}
          <div {% include "frontend/partials/table_responsive_attrs.html" %}>
            {% include "frontend/partials/button_icon.html" with icon="icons/pencil-alt.svg" unicorn_action="show_update"|withparam:character_texture.pk title=_("Edit") aria_label=_("Edit") %}
            {% include "frontend/partials/button_icon.html" with icon="icons/trash.svg" unicorn_action="delete"|withparam:character_texture.pk title=_("Delete") aria_label=_("Delete") %}
          </div>
          </td>
      </tr>
    {% endfor %}
    </tbody>

</table>

frontend/templates/unicorn/players-create.html
{% load i18n %}

{% if unicorn.errors %}
    {% include 'frontend/partials/error.html' %}
 {% endif %}

{% include "frontend/partials/heading.html" with title=_("Create Player") %}

<form u:submit.prevent="validate_and_create" id="add_player" aria-label="{% translate "Create player" %}"
{% include "frontend/partials/form_attrs.html" %}>

{% include "frontend/partials/form_input.html" with label=_("Name") id="username" unicorn_model="username" %}
{% include "frontend/partials/form_input.html" with type="email" label=_("Email address") id="email" unicorn_model="email" %}
{% include "frontend/partials/form_input.html" with label=_("Description") id="comment" unicorn_model="comment" %}

{% include "frontend/partials/form_buttons.html" %}

</form>

frontend/templates/unicorn/players.html
{% load frontend %}
{% load i18n %}
{% load static %}

{% include "frontend/partials/heading.html" with title=_("Players") button_label=_("Create Player") button_aria_label=_("Create Player") button_unicorn_action="show_create" %}

<table aria-label="{% translate "Player list" %}" {% include "frontend/partials/table_attrs.html" %}>

    <thead>
    <tr {% include "frontend/partials/table_head_row_attrs.html" %}>
      {% include "frontend/partials/table_head_col.html" with title=_("Name") %}
      {% include "frontend/partials/table_head_col.html" with title=_("Email address") %}
      {% include "frontend/partials/table_head_col.html" with title=_("Description") %}
      {% include "frontend/partials/table_head_col.html" with title=_("World memberships") %}
      {% include "frontend/partials/table_head_col.html" with title=_("Actions") align="right" %}
    </tr>
    </thead>

    <tbody {% include "frontend/partials/table_body_attrs.html" %}>
    {% for player in object_list %}
      <tr {% include "frontend/partials/table_row_attrs.html" %}>
        {% include "frontend/partials/table_cell.html" with title=_("Username") content=player.username %}
        {% include "frontend/partials/table_cell.html" with title=_("Email address") content=player.email %}
        {% if player.comment %}
        {% include "frontend/partials/table_cell.html" with title=_("Description") content=player.comment %}
        {% else %}
          <td class="hidden lg:table-cell"></td>
        {% endif %}
        {% if player.worlds.all %}
          {% include "frontend/partials/table_cell.html" with title=_("World memberships") content=player.worlds.all|join:", " %}
        {% else %}
          <td class="hidden lg:table-cell"></td>
        {% endif %}
        <td {% include "frontend/partials/table_cell_attrs.html" with type="actions" %}>
          {% include "frontend/partials/table_actions_header.html" %}
          <div {% include "frontend/partials/table_responsive_attrs.html" %}>
            {% include "frontend/partials/button_icon.html" with icon="icons/pencil-alt.svg" unicorn_action="show_update"|withparam:player.pk title=_("Edit") aria_label=_("Edit") %}
            {% include "frontend/partials/button_icon.html" with icon="icons/trash.svg" unicorn_action="delete"|withparam:player.pk title=_("Delete") aria_label=_("Delete") %}
          </div>
          </td>
      </tr>
    {% endfor %}
    </tbody>

</table>

frontend/templates/unicorn/tags-update.html
{% load i18n %}

{% if unicorn.errors %}
  {% include 'frontend/partials/error.html' %}
{% endif %}

{% include "frontend/partials/heading.html" with title=_("Edit Tag") %}

  <form u:submit.prevent="validate_and_update" id="update_tag" aria-label="{% translate "Edit tag" %}"
    {% include "frontend/partials/form_attrs.html" %}>

    {% include "frontend/partials/form_input.html" with label=_("Tag name") id="name" unicorn_model="name" %}
    {% include "frontend/partials/form_input.html" with type="text" label=_("Description") id="email" unicorn_model="description" %}

    {% include "frontend/partials/form_buttons.html" %}
  </form>

frontend/templates/unicorn/worlds-create.html
{% load i18n %}
{% load static %}

{% if unicorn.errors %}
  {% include 'frontend/partials/error.html' %}
{% endif %}

{% include "frontend/partials/heading.html" with title=_("Create World") %}

  <form u:submit.prevent="validate_and_create" id="add_world" aria-label="{% translate "Create world" %}"
      {% include "frontend/partials/form_attrs.html" %}>

    {% include "frontend/partials/form_input.html" with label=_("Name") id="name" unicorn_model="name" %}
    {% include "frontend/partials/form_input.html" with label=_("Description") id="description" unicorn_model="description" %}
    {% include "frontend/partials/form_input.html" with label=_("URL") id="url" unicorn_model="url" %}

    {% include "frontend/partials/form_buttons.html" %}

  </form>